### ISSUE TITLE
ClassNotFoundException on DefaultGeneratorStrategy override

### ISSUE THREAD

**Issue by ssudekum** [kxbmap/sbt-jooq#15]
When attempting to implement my custom override of DefaultGeneratorStrategy I receive this error:

```
Oct 31, 2018 4:06:56 PM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : /var/folders/jx/vxtx6m317_lb7_gzflbf7pwc0000gp/T/jooq-codegen-8265546994763137693.xml
Oct 31, 2018 4:06:57 PM org.jooq.tools.JooqLogger error
SEVERE: Cannot read /var/folders/jx/vxtx6m317_lb7_gzflbf7pwc0000gp/T/jooq-codegen-8265546994763137693.xml. Error : com.[omitted].jooq.codegen.CurrentStateInterfaceStrategy
java.lang.ClassNotFoundException: com.[omitted].jooq.codegen.CurrentStateInterfaceStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jooq.util.GenerationTool.loadClass(GenerationTool.java:679)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:289)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
	at org.jooq.util.GenerationTool.main(GenerationTool.java:175)

java.lang.RuntimeException: jOOQ codegen failure: 255
	at scala.sys.package$.error(package.scala:27)
	at com.github.kxbmap.sbt.jooq.JooqCodegen$$anonfun$codegenTask$1.apply(JooqCodegen.scala:95)
	at com.github.kxbmap.sbt.jooq.JooqCodegen$$anonfun$codegenTask$1.apply(JooqCodegen.scala:87)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:jooqCodegen) jOOQ codegen failure: 255
[error] Total time: 25 s, completed Oct 31, 2018 4:06:57 PM
```

Here is the relevant xml configuration being used

```
<generator>
        <strategy>
            <name>com.[omitted].jooq.codegen.CurrentStateInterfaceStrategy</name>
        </strategy>
        ...
```

I've tried consuming my Strategy class as an external dependency with no luck. I've experienced this error using both v0.3.0 and v 0.3.3.

**Comment by ssudekum** [comment]
http://www.jooq.org/doc/3.9/manual/code-generation/codegen-generatorstrategy/

**Comment by kxbmap** [comment]
Custom class should included in `jooq` scope classpath.

Please refer to this scripted-test:
https://github.com/kxbmap/sbt-jooq/tree/v0.4.0/src/sbt-test/sbt-jooq/module-deps

In above case, `upstream` project contains custom strategy and `app` project depends on `upstream` project.

```scala
lazy val app = project
  ...
  .dependsOn(upstream % "jooq")
```

**Comment by ssudekum** [comment]
@kxbmap AH that fixed it! Thanks so much.
