### ISSUE TITLE
Errors blocks compiling

### ISSUE THREAD

**Issue by zhongdj** [kxbmap/sbt-jooq#17]
I am using sbt 1.2.6 and scala 2.12.7 and ```addSbtPlugin("com.github.kxbmap" % "sbt-jooq" % "0.4.0")``` to generate source code. But while I am running ```sbt compie```, it always give errors as following:
```
[error] java.lang.RuntimeException: The incremental compiler requires absolute sources, but some were relative: target/scala-2.12/src_managed/main/com/gos/auth/jooq/Tables.scala and 12 others
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at sbt.internal.inc.IncrementalCommon.checkAbsolute(IncrementalCommon.scala:359)
[error] 	at sbt.internal.inc.IncrementalCommon.invalidateInitial(IncrementalCommon.scala:325)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:68)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1429)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1403)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) The incremental compiler requires absolute sources, but some were relative: target/scala-2.12/src_managed/main/com/gos/auth/jooq/Tables.scala and 12 others
[error] Total time: 21 s, completed Dec 7, 2018 9:19:47 PM
```

**Comment by kxbmap** [comment]
Thank you for reporting.

I fixed the part that seems to be the cause of the issue.
Could you confirm to the snapshot version fixes the issue?

```scala
resolver += Resolver.sonatypeRepo("snapshot")
addSbtPlugin("com.github.kxbmap" % "sbt-jooq" % "0.4.1-SNAPSHOT")
```

**Comment by kxbmap** [comment]
Version 0.4.1 that maybe fix the problem was released.
Please reopen this issue if problem not resolved.
